title: Bayesian Thinking and Ecology Workshop
logo: bayesecology.jpg
description: Learn from experts how they use Bayesian methods in their own research, get to know their tools, and apply the newly learned methods in a group project.
<a href="https://dhugpeter.github.io/EcoBayesThinking/#application"> <b> How to apply </b> </a>
theme: jekyll-theme-minimal
