title: Bayesian Thinking and Ecology Workshop
logo: bayesecology.jpg
description: Learn from experts how they use Bayesian methods in their own research, get to know their tools, and apply the newly learned methods in a group project.
theme: jekyll-theme-minimal
